apiVersion: v1
kind: Service
metadata:
  name: {{ include "secrets-init-webhook.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "secrets-init-webhook.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: https
      port: 443
      targetPort: https
      protocol: TCP
    - name: metrics
      port: {{ .Values.webhook.metricsPort }}
      targetPort: metrics
      protocol: TCP
  selector:
    {{- include "secrets-init-webhook.selectorLabels" . | nindent 4 }}
